/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CurrencyConverter;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        UserData userdata = new UserData();
        userdata.addUser("admin", "admin", true);
        userdata.addUser("guest", "guest", false);
        CurrencyData currencyData= new CurrencyData();
        currencyData.readFromFile("defaultData.txt");
        
        new LogInPage(userdata, currencyData);
    }
}
